name = "pilkingtonelectrical"
main = "dist/server/server.js"
compatibility_date = "2026-06-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"

[[kv_namespaces]]
binding = "REVIEWS_CACHE"
id = "e747af2b614f4d5d990edab2e3a9d847"
