name = "pilkingtonelectrical"
compatibility_date = "2026-07-24"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

[observability]
enabled = true

[assets]
directory = ".output/public"

[[kv_namespaces]]
binding = "REVIEWS_CACHE"
id = "e747af2b614f4d5d990edab2e3a9d847"

[[routes]]
pattern = "pilkingtonelectrical.com.au"
custom_domain = true

[[routes]]
pattern = "www.pilkingtonelectrical.com.au/*"
zone_name = "pilkingtonelectrical.com.au"
